# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |global_vbox|
    global_vbox.customize ["modifyvm", :id, "--graphicscontroller", "none"]
    global_vbox.customize ["modifyvm", :id, "--audio", "none"]
    global_vbox.memory = 4096
    global_vbox.cpus = 4
  end
  
  config.vm.provision "file" do |bootstrap_copy_keys|
    bootstrap_copy_keys.source = "zucchini-configs/keys"
    bootstrap_copy_keys.destination = "~/keys"
  end

  config.vm.provision "shell" do |bootstrap_ssh_keys|
    bootstrap_ssh_keys.name = "Copying GitHub deploy keys"
    bootstrap_ssh_keys.privileged = false
    bootstrap_ssh_keys.inline = <<-SHELL
      cp -r ${HOME}/keys/github/* ${HOME}/.ssh
    SHELL
  end

   config.vm.define "zucchinisys" do |node|
    node.vm.synced_folder "..\\..\\..\\..\\dev", "/vagrant", disabled: false
    node.vm.box = "bento/fedora-38"
    node.vm.hostname = "zucchinisys"
    node.vm.network "private_network", ip: "192.168.100.101", virtualbox__intnet: "zucchinisys-net"
    config.vm.provider "virtualbox" do |node_vbox|
      node_vbox.name = "zucchinisys"
    end
  end
end
