# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vbox|
      vbox.customize ["modifyvm", :id, "--graphicscontroller", "none"]
      vbox.customize ["modifyvm", :id, "--audio", "none"]
      vbox.memory = 2048
      vbox.cpus = 2
    end
  
    ssh_pub_key = ""
    config.vm.provision "shell" do |shell|
      shell.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  
    (1..3).each do |i|
      config.vm.define "dev-kube00#{i}" do |node|
        node.vm.synced_folder ".", "/vagrant", disabled: true
        node.vm.box = "zucchini/base-centos-7"
        node.vm.hostname = "dev-kube00#{i}"
        node.vm.network "private_network", ip: "192.168.100.10#{i}", virtualbox__intnet: "kubenetwork"
        node.vm.provision "shell" do |shell|
          shell.env = {"VAGRANT_KUBELET_NODE_IP" => "192.168.100.10#{i}"}
          shell.inline = <<-SHELL
            echo "$VAGRANT_KUBELET_NODE_IP" > /tmp/vagrant_kubelet_nodeip
          SHELL
        end
        node.vm.provider "virtualbox" do |vbox|
          vbox.name = "dev-kube00#{i}"
        end
      end        
    end
  end