# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |global_vbox|
    global_vbox.customize ["modifyvm", :id, "--graphicscontroller", "none"]
    global_vbox.customize ["modifyvm", :id, "--audio", "none"]
    global_vbox.memory = 4096
    global_vbox.cpus = 6
  end

  ssh_pub_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBh93LCERUP0lG79QiC0kuX/047xcweAHUu6LGuoj2DI Samuelito Key v3 - ed25519"
  config.vm.provision "shell" do |shell|
    shell.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  (1..3).each do |i|
    config.vm.define "dev-node00#{i}" do |node|
      node.vm.synced_folder ".", "/vagrant", disabled: true
      node.vm.box = "bento/centos-8"
      node.vm.hostname = "dev-node00#{i}"
      node.vm.network "private_network", ip: "192.168.100.10#{i}", virtualbox__intnet: "zucchini_test"
      node.vm.provider "virtualbox" do |vbox|
        vbox.name = "dev-node00#{i}"
      end
    end        
  end
end
