# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |global_vbox|
    global_vbox.customize ["modifyvm", :id, "--graphicscontroller", "none"]
    global_vbox.customize ["modifyvm", :id, "--audio", "none"]
    global_vbox.memory = 4096
    global_vbox.cpus = 6
  end

  ssh_pub_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBh93LCERUP0lG79QiC0kuX/047xcweAHUu6LGuoj2DI Samuelito Key v3 - ed25519"
  config.vm.provision "shell" do |shell|
    shell.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "dev-node001" do |node|
    node.vm.synced_folder ".", "/vagrant", disabled: true
    node.vm.box = "zucchini/base-centos-8"
    node.vm.hostname = "dev-node001"
    node.vm.network "private_network", ip: "10.2.2.102", virtualbox__intnet: "zucchini"
    config.vm.provider "virtualbox" do |node_vbox|
      node_vbox.name = "dev-node001"
    end
  end
end